// Generated by LiveScript 1.4.0
(function(){
  var user, pass, out$ = typeof exports != 'undefined' && exports || this;
  out$.user = user = process.env.CORNELL_NETID_USERNAME;
  out$.pass = pass = process.env.CORNELL_NETID_PASSWORD;
}).call(this);
